/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyDatagridRouteImport } from './routes/why-datagrid'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services.mobile-app-development'
import { Route as ServicesGlobalCapabilityCentersDedicatedTeamsRouteImport } from './routes/services.global-capability-centers-dedicated-teams'
import { Route as ServicesCustomSoftwareDevelopmentRouteImport } from './routes/services.custom-software-development'
import { Route as ServicesAiMlDevelopmentRouteImport } from './routes/services.ai-ml-development'

const WhyDatagridRoute = WhyDatagridRouteImport.update({
  id: '/why-datagrid',
  path: '/why-datagrid',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/services/mobile-app-development',
    path: '/services/mobile-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesGlobalCapabilityCentersDedicatedTeamsRoute =
  ServicesGlobalCapabilityCentersDedicatedTeamsRouteImport.update({
    id: '/services/global-capability-centers-dedicated-teams',
    path: '/services/global-capability-centers-dedicated-teams',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomSoftwareDevelopmentRoute =
  ServicesCustomSoftwareDevelopmentRouteImport.update({
    id: '/services/custom-software-development',
    path: '/services/custom-software-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAiMlDevelopmentRoute = ServicesAiMlDevelopmentRouteImport.update({
  id: '/services/ai-ml-development',
  path: '/services/ai-ml-development',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/why-datagrid': typeof WhyDatagridRoute
  '/services/ai-ml-development': typeof ServicesAiMlDevelopmentRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/global-capability-centers-dedicated-teams': typeof ServicesGlobalCapabilityCentersDedicatedTeamsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/why-datagrid': typeof WhyDatagridRoute
  '/services/ai-ml-development': typeof ServicesAiMlDevelopmentRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/global-capability-centers-dedicated-teams': typeof ServicesGlobalCapabilityCentersDedicatedTeamsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/why-datagrid': typeof WhyDatagridRoute
  '/services/ai-ml-development': typeof ServicesAiMlDevelopmentRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/global-capability-centers-dedicated-teams': typeof ServicesGlobalCapabilityCentersDedicatedTeamsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/certification'
    | '/contact'
    | '/leadership'
    | '/why-datagrid'
    | '/services/ai-ml-development'
    | '/services/custom-software-development'
    | '/services/global-capability-centers-dedicated-teams'
    | '/services/mobile-app-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies'
    | '/certification'
    | '/contact'
    | '/leadership'
    | '/why-datagrid'
    | '/services/ai-ml-development'
    | '/services/custom-software-development'
    | '/services/global-capability-centers-dedicated-teams'
    | '/services/mobile-app-development'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/certification'
    | '/contact'
    | '/leadership'
    | '/why-datagrid'
    | '/services/ai-ml-development'
    | '/services/custom-software-development'
    | '/services/global-capability-centers-dedicated-teams'
    | '/services/mobile-app-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CertificationRoute: typeof CertificationRoute
  ContactRoute: typeof ContactRoute
  LeadershipRoute: typeof LeadershipRoute
  WhyDatagridRoute: typeof WhyDatagridRoute
  ServicesAiMlDevelopmentRoute: typeof ServicesAiMlDevelopmentRoute
  ServicesCustomSoftwareDevelopmentRoute: typeof ServicesCustomSoftwareDevelopmentRoute
  ServicesGlobalCapabilityCentersDedicatedTeamsRoute: typeof ServicesGlobalCapabilityCentersDedicatedTeamsRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-datagrid': {
      id: '/why-datagrid'
      path: '/why-datagrid'
      fullPath: '/why-datagrid'
      preLoaderRoute: typeof WhyDatagridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/services/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/global-capability-centers-dedicated-teams': {
      id: '/services/global-capability-centers-dedicated-teams'
      path: '/services/global-capability-centers-dedicated-teams'
      fullPath: '/services/global-capability-centers-dedicated-teams'
      preLoaderRoute: typeof ServicesGlobalCapabilityCentersDedicatedTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-software-development': {
      id: '/services/custom-software-development'
      path: '/services/custom-software-development'
      fullPath: '/services/custom-software-development'
      preLoaderRoute: typeof ServicesCustomSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-ml-development': {
      id: '/services/ai-ml-development'
      path: '/services/ai-ml-development'
      fullPath: '/services/ai-ml-development'
      preLoaderRoute: typeof ServicesAiMlDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CertificationRoute: CertificationRoute,
  ContactRoute: ContactRoute,
  LeadershipRoute: LeadershipRoute,
  WhyDatagridRoute: WhyDatagridRoute,
  ServicesAiMlDevelopmentRoute: ServicesAiMlDevelopmentRoute,
  ServicesCustomSoftwareDevelopmentRoute:
    ServicesCustomSoftwareDevelopmentRoute,
  ServicesGlobalCapabilityCentersDedicatedTeamsRoute:
    ServicesGlobalCapabilityCentersDedicatedTeamsRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
